name: MVS Creatives
favicon: null
layout_spectrum: 0.8835126
typography_spectrum: 0.86201
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#2F4A6F'
    - '#0066FF'
    - '#7997C7'
  brandStrength: 0
  lightness: 0.7096774
  saturation: 0.6899642
  rhythmicContrast: 0.2598566
purpose: []
