layout_spectrum: 0.9137439676707076
typography_spectrum: 0.8950057615314859
color:
  lightness: 0.6530903636920496
  brandColors:
    - '#FF8000'
    - '#FFD933'
    - '#CCCC52'
    - '#8FB359'
    - '#192B33'
  saturation: 0.6657831121456469
  brandStrength: 0.662927873322814
  rhythmicContrast: 0.3474169569750234
name: MVS Creatives
analytics: {}
purpose: []
github: true
description: MVS
cta:
  bucket: null
  version: null
  domain: null
author:
  name: 'mvs '
  url: 'http://www.mvs-musicvisionsound.com'
  email: michelle.scott@musicvisionsound.com
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/6b9b86e4-293c-4a6e-a2d5-fbd7a3958611.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/6b9b86e4-293c-4a6e-a2d5-fbd7a3958611.png
    metadata:
      author: []
      '@context': 'http://schema.org'
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d4021af6-0063-4a00-aa25-91c8f28490dc.png
content_rating:
  adult: false
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
opengraph: {}
title: MUSIC VISION SOUND
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fdbca445-020c-4cd4-97de-8e3307a5f371.png
