collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6899642
  brandStrength: 0
  rhythmicContrast: 0.2598566
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#2F4A6F'
    - '#0066FF'
    - '#7997C7'
  lightness: 0.7096774
typography_spectrum: 0.3082437
layout_spectrum: 0.8835126
name: MVS Creatives
