layout_spectrum: 0.1454559
typography_spectrum: 0.387553
color:
  saturation: 0.7448779
  lightness: 0.2964859
  brandStrength: 0.4642493
  rhythmicContrast: 0.1498789
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: MVS Creatives
