collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8082438
  brandStrength: 0.09139785
  lightness: 0.1111111
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#2F4A6F'
    - '#0066FF'
    - '#7997C7'
  rhythmicContrast: 0.1577061
typography_spectrum: 0.890681
layout_spectrum: 0.8888889
name: MVS Creatives
