collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.890681
color:
  saturation: 0.8082438
  brandStrength: 0.1541219
  lightness: 0.1111111
  brandColors:
    - '#FFFFFF'
    - '#050505'
    - '#8B0304'
    - '#E2C0C0'
    - '#A84142'
  rhythmicContrast: 0.1577061
layout_spectrum: 0.8888889
name: MVS Creatives
